In [1]:
import pandas as pd

bank_note_data = pd.read_csv("https://raw.githubusercontent.com/dphi-official/Datasets/master/bank_note_data/training_set_label.csv" )

bank_note_data.head()

VWTI     SWTI     CWTI        EI  Class
0  2.2634  -4.4862   3.6558 -0.612510      0
1  3.2718   1.7837   2.1161  0.613340      0
2 -3.9411 -12.8792  13.0597 -3.312500      1
3  0.5195  -3.2633   3.0895 -0.984900      0
4  2.5698  -4.4076   5.9856  0.078002      0

In [2]:
Y = bank_note_data['Class']
featureCols = ['VWTI', 'SWTI', 'CWTI', 'EI']
X = bank_note_data[featureCols]

In [3]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, 
                                test_size=0.33, 
                                random_state=0)

In [4]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(x_train,y_train)
y_pred=logreg.predict(x_test)

In [5]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9861878453038674


In [6]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
model = XGBClassifier()
model.fit(x_train, y_train)
y_pred=model.predict(x_test)
print(accuracy_score(y_test, y_pred)*100)

99.4475138121547


In [7]:
test_data = pd.read_csv('https://raw.githubusercontent.com/dphi-official/Datasets/master/bank_note_data/testing_set_label.csv')

In [8]:
YTest = logreg.predict(test_data)

In [9]:
YTest

array([1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0], dtype=int64)

In [10]:
YTEst = model.predict(test_data)
YTEst

array([1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0], dtype=int64)

In [11]:
Dataset = bank_note_data.values

In [13]:
X = Dataset[:, 0:4]
Y = Dataset[:, 4]
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
X_scale = min_max_scaler.fit_transform(X)

X_scale

array([[0.68382391, 0.35040542, 0.38520258, 0.72157724],
       [0.7579726 , 0.58697596, 0.31887479, 0.83304145],
       [0.22760061, 0.03372788, 0.79030736, 0.47607227],
       ...,
       [0.73372942, 0.79926651, 0.18562518, 0.69688571],
       [0.66186019, 0.78146495, 0.25258233, 0.83762696],
       [0.50811121, 0.90912075, 0.06780537, 0.22092801]])

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_val, Y_train, Y_val = train_test_split(X_scale, Y, test_size=0.5)

In [16]:
from keras.models import Sequential
from keras.layers import Dense

model = Sequential([    Dense(32, activation='relu', input_shape=(4,)),    Dense(32, activation='relu'),    Dense(1, activation='sigmoid'),])
model.compile(optimizer='adam',              loss='binary_crossentropy',              metrics=['accuracy'])
hist = model.fit(X_train, Y_train,          batch_size=32, epochs=150,          validation_data=(X_val, Y_val))



Train on 548 samples, validate on 548 samples
Epoch 1/150
548/548 [==============================] - 2s 4ms/step - loss: 0.6684 - acc: 0.6241 - val_loss: 0.6578 - val_acc: 0.5420
Epoch 2/150
548/548 [==============================] - 0s 72us/step - loss: 0.6368 - acc: 0.5785 - val_loss: 0.6460 - val_acc: 0.5584
Epoch 3/150
548/548 [==============================] - 0s 58us/step - loss: 0.6187 - acc: 0.6168 - val_loss: 0.6270 - val_acc: 0.6022
Epoch 4/150
548/548 [==============================] - 0s 64us/step - loss: 0.5969 - acc: 0.6460 - val_loss: 0.6056 - val_acc: 0.6314
Epoch 5/150
548/548 [==============================] - 0s 56us/step - loss: 0.5712 - acc: 0.7080 - val_loss: 0.5808 - val_acc: 0.7190
Epoch 6/150
548/548 [==============================] - 0s 58us/step - loss: 0.5448 - acc: 0.7372 - val_loss: 0.5593 - val_acc: 0.7318
Epoch 7/150
548/548 [==============================] - 0s 56us/step - loss: 0.5173 - acc: 0.7847 - val_loss: 0.5332 - val_acc: 0.7719
Epoch 8/150
548/

Epoch 60/150
548/548 [==============================] - 0s 66us/step - loss: 0.0588 - acc: 0.9872 - val_loss: 0.0593 - val_acc: 0.9909
Epoch 61/150
548/548 [==============================] - 0s 56us/step - loss: 0.0535 - acc: 0.9836 - val_loss: 0.0569 - val_acc: 0.9927
Epoch 62/150
548/548 [==============================] - 0s 58us/step - loss: 0.0519 - acc: 0.9854 - val_loss: 0.0552 - val_acc: 0.9927
Epoch 63/150
548/548 [==============================] - 0s 56us/step - loss: 0.0505 - acc: 0.9836 - val_loss: 0.0536 - val_acc: 0.9927
Epoch 64/150
548/548 [==============================] - 0s 62us/step - loss: 0.0491 - acc: 0.9872 - val_loss: 0.0519 - val_acc: 0.9945
Epoch 65/150
548/548 [==============================] - 0s 62us/step - loss: 0.0478 - acc: 0.9836 - val_loss: 0.0503 - val_acc: 0.9945
Epoch 66/150
548/548 [==============================] - 0s 67us/step - loss: 0.0462 - acc: 0.9891 - val_loss: 0.0490 - val_acc: 0.9945
Epoch 67/150
548/548 [==============================] -

548/548 [==============================] - 0s 60us/step - loss: 0.0164 - acc: 0.9964 - val_loss: 0.0180 - val_acc: 0.9964
Epoch 121/150
548/548 [==============================] - 0s 67us/step - loss: 0.0158 - acc: 0.9964 - val_loss: 0.0179 - val_acc: 0.9964
Epoch 122/150
548/548 [==============================] - 0s 66us/step - loss: 0.0152 - acc: 0.9964 - val_loss: 0.0175 - val_acc: 0.9964
Epoch 123/150
548/548 [==============================] - 0s 64us/step - loss: 0.0146 - acc: 0.9964 - val_loss: 0.0172 - val_acc: 0.9964
Epoch 124/150
548/548 [==============================] - 0s 64us/step - loss: 0.0145 - acc: 0.9964 - val_loss: 0.0175 - val_acc: 0.9964
Epoch 125/150
548/548 [==============================] - 0s 62us/step - loss: 0.0144 - acc: 0.9964 - val_loss: 0.0169 - val_acc: 0.9964
Epoch 126/150
548/548 [==============================] - 0s 62us/step - loss: 0.0144 - acc: 0.9964 - val_loss: 0.0166 - val_acc: 0.9964
Epoch 127/150
548/548 [==============================] - 0s 76

In [17]:
_, accuracy = model.evaluate(X_val, Y_val)
print('Accuracy: %.2f' % (accuracy*100))

548/548 [==============================] - 0s 24us/step
Accuracy: 99.82


In [18]:
YTEST = model.predict(test_data)

In [22]:
import numpy as np

np.round(YTEST)

array([[1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],